# Generated by Django 5.2.7 on 2025-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=8, null=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='admin_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='admin_permissions_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rail-Me Express 101', 'Rail-Me Express 101 (Lagos to Abuja)'), ('Rail-Me Express 202', 'Rail-Me Express 202 (Abeokuta to Kaduna)'), ('Rail-Me Express 303', 'Rail-Me Express 303 (Ibadan to Kano)'), ('Rail-Me Express 404', 'Rail-Me Express 404 (Abuja to Lagos)'), ('Rail-Me Express 505', 'Rail-Me Express 505 (Kaduna to Abeokuta)')], max_length=100)),
                ('departure_station', models.CharField(choices=[('Abeokuta Central', 'Abeokuta Central'), ('Lagos Terminus', 'Lagos Terminus'), ('Ibadan Station', 'Ibadan Station'), ('Abuja Idu Station', 'Abuja Idu Station'), ('Kaduna Station', 'Kaduna Station'), ('Kano Station', 'Kano Station')], max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_station', models.CharField(choices=[('Abeokuta Central', 'Abeokuta Central'), ('Lagos Terminus', 'Lagos Terminus'), ('Ibadan Station', 'Ibadan Station'), ('Abuja Idu Station', 'Abuja Idu Station'), ('Kaduna Station', 'Kaduna Station'), ('Kano Station', 'Kano Station')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_seats', models.IntegerField(default=100)),
                ('seats_remaining', models.IntegerField(default=100)),
            ],
            options={
                'unique_together': {('name', 'departure_station', 'destination')},
            },
        ),
    ]
