# Generated by Django 5.2.7 on 2025-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_train_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(choices=[('Rail-Me Express 101', 'Rail-Me Express 101 (Lagos to Abuja)'), ('Rail-Me Express 202', 'Rail-Me Express 202 (Abeokuta to Kaduna)'), ('Rail-Me Express 303', 'Rail-Me Express 303 (Ibadan to Kano)'), ('Rail-Me Express 404', 'Rail-Me Express 404 (Abuja to Ibadan)'), ('Rail-Me Express 505', 'Rail-Me Express 505 (Kaduna to Abeokuta)'), ('Rail-Me Express 505', 'Rail-Me Express 606 (Abuja to Abeokuta)'), ('Rail-Me Express 505', 'Rail-Me Express 707 (Kaduna to Ibadan)'), ('Rail-Me Express 505', 'Rail-Me Express 808 (Lagos to Ibadan)'), ('Rail-Me Express 505', 'Rail-Me Express 909 (Kaduna to Kano)')], max_length=100),
        ),
    ]
