# Generated by Django 5.2.7 on 2025-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_train_arrival_time_train_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.DateTimeField(default='2025-10-23T14:44:32.675123+01:00'),
            preserve_default=False,
        ),
    ]
