# Generated by Django 5.2.7 on 2025-10-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_remove_train_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_station',
            field=models.CharField(choices=[('Abeokuta Central', 'Abeokuta Central'), ('Katsina Staion', 'Katsina Terminus'), ('Jigawa Station', 'Jigawa Station'), ('Abuja Idu Station', 'Abuja Idu Station'), ('Kano Station', 'Kano Station'), ('Kaduna Station', 'Kaduna Station'), ('Kebbi Station', 'Kebbi Station'), ('Sokoto Station', 'Sokoto Station'), ('Zamfara Station', 'Zamfara Station'), ('Adamawa Station', 'Adamawa Station'), ('Bauchi Station', 'Bauchi Station'), ('Borno Station', 'Borno Station'), ('Gombe Station', 'Gombe Station'), ('Taraba Station', 'Taraba Station'), ('Yobe Station', 'Yobe Station'), ('Kogi Station', 'Kogi Station'), ('Benue Station', 'Benue Station'), ('Kwara Station', 'Kwara Station'), ('Nasarawa Station', 'Nasarawa Station'), ('Niger Station', 'Niger Station'), ('Plateau Station', 'Plateau Station')], max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_station',
            field=models.CharField(choices=[('Abeokuta Central', 'Abeokuta Central'), ('Katsina Staion', 'Katsina Terminus'), ('Jigawa Station', 'Jigawa Station'), ('Abuja Idu Station', 'Abuja Idu Station'), ('Kano Station', 'Kano Station'), ('Kaduna Station', 'Kaduna Station'), ('Kebbi Station', 'Kebbi Station'), ('Sokoto Station', 'Sokoto Station'), ('Zamfara Station', 'Zamfara Station'), ('Adamawa Station', 'Adamawa Station'), ('Bauchi Station', 'Bauchi Station'), ('Borno Station', 'Borno Station'), ('Gombe Station', 'Gombe Station'), ('Taraba Station', 'Taraba Station'), ('Yobe Station', 'Yobe Station'), ('Kogi Station', 'Kogi Station'), ('Benue Station', 'Benue Station'), ('Kwara Station', 'Kwara Station'), ('Nasarawa Station', 'Nasarawa Station'), ('Niger Station', 'Niger Station'), ('Plateau Station', 'Plateau Station')], max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(choices=[('Rail-Me Express 001', 'Rail-Me Express 001 (Abeokuta to Katsina)'), ('Rail-Me Express 002', 'Rail-Me Express 002 (Abeokuta to Kaduna)'), ('Rail-Me Express 003', 'Rail-Me Express 003 (Abeokuta to Kano)'), ('Rail-Me Express 004', 'Rail-Me Express 004 (Abeokuta to Jigawa)'), ('Rail-Me Express 005', 'Rail-Me Express 005 (Abeokuta to Abuja)'), ('Rail-Me Express 006', 'Rail-Me Express 006 (Abeokuta to Kebbi)'), ('Rail-Me Express 007', 'Rail-Me Express 007 (Abeokuta to Sokoto)'), ('Rail-Me Express 008', 'Rail-Me Express 008 (Abeokuta to Zamfara)'), ('Rail-Me Express 009', 'Rail-Me Express 009 (Abeokuta to Adamawa)'), ('Rail-Me Express 010', 'Rail-Me Express 010 (Abeokuta to Bauchi)'), ('Rail-Me Express 020', 'Rail-Me Express 020 (Abeokuta to Borno)'), ('Rail-Me Express 030', 'Rail-Me Express 030 (Abeokuta to Gombe)'), ('Rail-Me Express 040', 'Rail-Me Express 040 (Abeokuta to Taraba)'), ('Rail-Me Express 050', 'Rail-Me Express 050 (Abeokuta to Yobe)'), ('Rail-Me Express 060', 'Rail-Me Express 060 (Abeokuta to Kogi)'), ('Rail-Me Express 070', 'Rail-Me Express 070 (Abeokuta to Benue)'), ('Rail-Me Express 080', 'Rail-Me Express 080 (Abeokuta to Kwara)'), ('Rail-Me Express 090', 'Rail-Me Express 090 (Abeokuta to Nasarawa)'), ('Rail-Me Express 101', 'Rail-Me Express 101 (Abeokuta to Niger)'), ('Rail-Me Express 202', 'Rail-Me Express 202 (Abeokuta to Plateau)')], max_length=100),
        ),
    ]
