# Generated by Django 5.2.7 on 2025-10-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_train_arrival_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_station',
            field=models.CharField(choices=[('Abeokuta Central', 'Abeokuta Central'), ('Katsina Station', 'Katsina Station'), ('Jigawa Station', 'Jigawa Station'), ('Abuja Idu Station', 'Abuja Idu Station'), ('Kano Station', 'Kano Station'), ('Kaduna Station', 'Kaduna Station'), ('Kebbi Station', 'Kebbi Station'), ('Sokoto Station', 'Sokoto Station'), ('Zamfara Station', 'Zamfara Station'), ('Adamawa Station', 'Adamawa Station'), ('Bauchi Station', 'Bauchi Station'), ('Borno Station', 'Borno Station'), ('Gombe Station', 'Gombe Station'), ('Taraba Terminal', 'Taraba Terminal'), ('Yobe Station', 'Yobe Station'), ('Kogi Terminus', 'Kogi Terminus'), ('Benue Station', 'Benue Station'), ('Kwara Station', 'Kwara Station'), ('Nasarawa Station', 'Nasarawa Station'), ('Niger Station', 'Niger Station'), ('Plateau Station', 'Plateau Station')], max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_station',
            field=models.CharField(choices=[('Abeokuta Central', 'Abeokuta Central'), ('Katsina Station', 'Katsina Station'), ('Jigawa Station', 'Jigawa Station'), ('Abuja Idu Station', 'Abuja Idu Station'), ('Kano Station', 'Kano Station'), ('Kaduna Station', 'Kaduna Station'), ('Kebbi Station', 'Kebbi Station'), ('Sokoto Station', 'Sokoto Station'), ('Zamfara Station', 'Zamfara Station'), ('Adamawa Station', 'Adamawa Station'), ('Bauchi Station', 'Bauchi Station'), ('Borno Station', 'Borno Station'), ('Gombe Station', 'Gombe Station'), ('Taraba Terminal', 'Taraba Terminal'), ('Yobe Station', 'Yobe Station'), ('Kogi Terminus', 'Kogi Terminus'), ('Benue Station', 'Benue Station'), ('Kwara Station', 'Kwara Station'), ('Nasarawa Station', 'Nasarawa Station'), ('Niger Station', 'Niger Station'), ('Plateau Station', 'Plateau Station')], max_length=100),
        ),
    ]
