# Generated by Django 5.2.7 on 2025-10-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_train_arrival_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='name',
            new_name='train_name',
        ),
        migrations.AlterUniqueTogether(
            name='train',
            unique_together={('train_name', 'departure_station', 'destination')},
        ),
    ]
