# Generated by Django 5.2.7 on 2025-10-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_rename_name_train_train_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
