# Generated by Django 5.2.7 on 2025-10-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_admin_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_admin',
        ),
    ]
