# Generated by Django 5.2.7 on 2025-10-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
