# Generated by Django 5.2.7 on 2025-10-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0010_rename_name_train_train_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('reservation', 'reservation'), ('economy', 'Economy'), ('business', 'Business')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_services', to='admin_app.admin')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_app.train')),
            ],
            options={
                'unique_together': {('train', 'service_type')},
            },
        ),
    ]
