# Generated by Django 5.2.7 on 2025-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('economy', 'Economy'), ('business', 'Business')], max_length=20),
        ),
    ]
