# Generated by Django 5.2.7 on 2025-10-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('business', 'Business'), ('economy', 'Economy')], max_length=20),
        ),
    ]
