# Generated by Django 5.2.7 on 2025-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_time',
            field=models.DateTimeField(default='2025-10-23T12:00:00+01:00'),
            preserve_default=False,
        ),
    ]
