# Generated by Django 5.2.7 on 2025-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_booking_arrival_time_booking_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_time',
            field=models.DateTimeField(default='2025-10-23T14:44:32.675123+01:00'),
            preserve_default=False,
        ),
    ]
