# Generated by Django 5.2.7 on 2025-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0003_alter_booking_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=81500.0, max_digits=10),
        ),
    ]
