# Generated by Django 5.2.7 on 2025-10-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0005_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('economy', 'Economy'), ('business', 'Business')], default='reservation', max_length=20),
        ),
    ]
