# Generated by Django 5.2.7 on 2025-10-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0006_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='00000', max_digits=10),
            preserve_default=False,
        ),
    ]
